package app.vrtic.Model;

// default package
// Generated 09-May-2016 12:32:34 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aktivnost generated by hbm2java
 */
@Entity
@Table(name = "aktivnost", catalog = "tim9")
public class Aktivnost implements java.io.Serializable {

	private Integer idAktivnosti;
	private String naziv;
	private Integer brojDjece;
	private Integer cijena;
	private Set<Termin> termins = new HashSet<Termin>(0);
	private Set<Aktivnostidjeca> aktivnostidjecas = new HashSet<Aktivnostidjeca>(0);

	public Aktivnost() {
	}

	public Aktivnost(String naziv, Integer brojDjece, Integer cijena, Set<Termin> termins,
			Set<Aktivnostidjeca> aktivnostidjecas) {
		this.naziv = naziv;
		this.brojDjece = brojDjece;
		this.cijena = cijena;
		this.termins = termins;
		this.aktivnostidjecas = aktivnostidjecas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAktivnosti", unique = true, nullable = false)
	public Integer getIdAktivnosti() {
		return this.idAktivnosti;
	}

	public void setIdAktivnosti(Integer idAktivnosti) {
		this.idAktivnosti = idAktivnosti;
	}

	@Column(name = "Naziv")
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "BrojDjece")
	public Integer getBrojDjece() {
		return this.brojDjece;
	}

	public void setBrojDjece(Integer brojDjece) {
		this.brojDjece = brojDjece;
	}

	@Column(name = "cijena")
	public Integer getCijena() {
		return this.cijena;
	}

	public void setCijena(Integer cijena) {
		this.cijena = cijena;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aktivnost")
	public Set<Termin> getTermins() {
		return this.termins;
	}

	public void setTermins(Set<Termin> termins) {
		this.termins = termins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aktivnost")
	public Set<Aktivnostidjeca> getAktivnostidjecas() {
		return this.aktivnostidjecas;
	}

	public void setAktivnostidjecas(Set<Aktivnostidjeca> aktivnostidjecas) {
		this.aktivnostidjecas = aktivnostidjecas;
	}

}
