package app.vrtic.Model;

// default package
// Generated 09-May-2016 12:32:34 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Termin generated by hbm2java
 */
@Entity
@Table(name = "termin", catalog = "tim9")
public class Termin implements java.io.Serializable {

	private Integer idTermin;
	private Aktivnost aktivnost;
	private Grupa grupa;
	private String vrijemePocetka;
	private String vrijemeZavrsetka;
	private String dan;

	public Termin() {
	}

	public Termin(Aktivnost aktivnost, Grupa grupa, String vrijemePocetka, String vrijemeZavrsetka, String dan) {
		this.aktivnost = aktivnost;
		this.grupa = grupa;
		this.vrijemePocetka = vrijemePocetka;
		this.vrijemeZavrsetka = vrijemeZavrsetka;
		this.dan = dan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTermin", unique = true, nullable = false)
	public Integer getIdTermin() {
		return this.idTermin;
	}

	public void setIdTermin(Integer idTermin) {
		this.idTermin = idTermin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAktivnosti")
	public Aktivnost getAktivnost() {
		return this.aktivnost;
	}

	public void setAktivnost(Aktivnost aktivnost) {
		this.aktivnost = aktivnost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGrupe")
	public Grupa getGrupa() {
		return this.grupa;
	}

	public void setGrupa(Grupa grupa) {
		this.grupa = grupa;
	}

	@Column(name = "vrijemePocetka", length = 45)
	public String getVrijemePocetka() {
		return this.vrijemePocetka;
	}

	public void setVrijemePocetka(String vrijemePocetka) {
		this.vrijemePocetka = vrijemePocetka;
	}

	@Column(name = "vrijemeZavrsetka", length = 45)
	public String getVrijemeZavrsetka() {
		return this.vrijemeZavrsetka;
	}

	public void setVrijemeZavrsetka(String vrijemeZavrsetka) {
		this.vrijemeZavrsetka = vrijemeZavrsetka;
	}

	@Column(name = "dan", length = 45)
	public String getDan() {
		return this.dan;
	}

	public void setDan(String dan) {
		this.dan = dan;
	}

}
