package app.vrtic.modeli;

// default package
// Generated 09-May-2016 02:07:59 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AktivnostidjecaId generated by hbm2java
 */
@Embeddable
public class AktivnostidjecaId implements java.io.Serializable {

	private int idDijete;
	private int idAktivnosti;

	public AktivnostidjecaId() {
	}

	public AktivnostidjecaId(int idDijete, int idAktivnosti) {
		this.idDijete = idDijete;
		this.idAktivnosti = idAktivnosti;
	}

	@Column(name = "idDijete", nullable = false)
	public int getIdDijete() {
		return this.idDijete;
	}

	public void setIdDijete(int idDijete) {
		this.idDijete = idDijete;
	}

	@Column(name = "idAktivnosti", nullable = false)
	public int getIdAktivnosti() {
		return this.idAktivnosti;
	}

	public void setIdAktivnosti(int idAktivnosti) {
		this.idAktivnosti = idAktivnosti;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AktivnostidjecaId))
			return false;
		AktivnostidjecaId castOther = (AktivnostidjecaId) other;

		return (this.getIdDijete() == castOther.getIdDijete())
				&& (this.getIdAktivnosti() == castOther.getIdAktivnosti());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDijete();
		result = 37 * result + this.getIdAktivnosti();
		return result;
	}

}
