package app.vrtic.modeli;

// default package
// Generated 09-May-2016 12:32:34 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aktivnostidjeca generated by hbm2java
 */
@Entity
@Table(name = "aktivnostidjeca", catalog = "tim9")
public class Aktivnostidjeca implements java.io.Serializable {

	private AktivnostidjecaId id;
	private Aktivnost aktivnost;
	private Dijete dijete;

	public Aktivnostidjeca() {
	}

	public Aktivnostidjeca(AktivnostidjecaId id, Aktivnost aktivnost, Dijete dijete) {
		this.id = id;
		this.aktivnost = aktivnost;
		this.dijete = dijete;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idDijete", column = @Column(name = "idDijete", nullable = false)),
			@AttributeOverride(name = "idAktivnosti", column = @Column(name = "idAktivnosti", nullable = false)) })
	public AktivnostidjecaId getId() {
		return this.id;
	}

	public void setId(AktivnostidjecaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAktivnosti", nullable = false, insertable = false, updatable = false)
	public Aktivnost getAktivnost() {
		return this.aktivnost;
	}

	public void setAktivnost(Aktivnost aktivnost) {
		this.aktivnost = aktivnost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDijete", nullable = false, insertable = false, updatable = false)
	public Dijete getDijete() {
		return this.dijete;
	}

	public void setDijete(Dijete dijete) {
		this.dijete = dijete;
	}

}
