package app.vrtic.modeli;

// default package
// Generated 09-May-2016 02:07:59 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name = "korisnik", catalog = "tim9")
public class Korisnik implements java.io.Serializable {

	private int idKorisnika;
	private String ime;
	private String prezime;
	private String korisnickoIme;
	private String sifra;
	private String privilegije;
	private String brojTelefona;

	public Korisnik() {
	}

	public Korisnik(int idKorisnika) {
		this.idKorisnika = idKorisnika;
	}

	public Korisnik(int idKorisnika, String ime, String prezime, String korisnickoIme, String sifra, String privilegije,
			String brojTelefona) {
		this.idKorisnika = idKorisnika;
		this.ime = ime;
		this.prezime = prezime;
		this.korisnickoIme = korisnickoIme;
		this.sifra = sifra;
		this.privilegije = privilegije;
		this.brojTelefona = brojTelefona;
	}

	@Id

	@Column(name = "idKorisnika", unique = true, nullable = false)
	public int getIdKorisnika() {
		return this.idKorisnika;
	}

	public void setIdKorisnika(int idKorisnika) {
		this.idKorisnika = idKorisnika;
	}

	@Column(name = "Ime")
	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	@Column(name = "Prezime")
	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	@Column(name = "KorisnickoIme")
	public String getKorisnickoIme() {
		return this.korisnickoIme;
	}

	public void setKorisnickoIme(String korisnickoIme) {
		this.korisnickoIme = korisnickoIme;
	}

	@Column(name = "Sifra")
	public String getSifra() {
		return this.sifra;
	}

	public void setSifra(String sifra) {
		this.sifra = sifra;
	}

	@Column(name = "Privilegije")
	public String getPrivilegije() {
		return this.privilegije;
	}

	public void setPrivilegije(String privilegije) {
		this.privilegije = privilegije;
	}

	@Column(name = "BrojTelefona", length = 45)
	public String getBrojTelefona() {
		return this.brojTelefona;
	}

	public void setBrojTelefona(String brojTelefona) {
		this.brojTelefona = brojTelefona;
	}

}
